# Generated by Django 4.2.10 on 2024-03-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
                ('simage', models.ImageField(upload_to='s_pic')),
                ('sdesc', models.TextField()),
            ],
        ),
    ]
